package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Categorieprodveterinaire generated by hbm2java
 */
@Entity
@Table(name = "categorieprodveterinaire", schema = "public")
public class Categorieprodveterinaire implements java.io.Serializable {

	private int idcatprodveterinaire;
	private String nom;
	private Set<Produitveterinaire> produitveterinaires = new HashSet(0);

	public Categorieprodveterinaire() {
	}

	public Categorieprodveterinaire(int idcatprodveterinaire) {
		this.idcatprodveterinaire = idcatprodveterinaire;
	}

	public Categorieprodveterinaire(int idcatprodveterinaire, String nom, Set<Produitveterinaire> produitveterinaires) {
		this.idcatprodveterinaire = idcatprodveterinaire;
		this.nom = nom;
		this.produitveterinaires = produitveterinaires;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idcatprodveterinaire", unique = true, nullable = false)
	public int getIdcatprodveterinaire() {
		return this.idcatprodveterinaire;
	}

	public void setIdcatprodveterinaire(int idcatprodveterinaire) {
		this.idcatprodveterinaire = idcatprodveterinaire;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorieprodveterinaire")
	@JsonIgnoreProperties("categorieprodveterinaire")
	public Set<Produitveterinaire> getProduitveterinaires() {
		return this.produitveterinaires;
	}

	public void setProduitveterinaires(Set<Produitveterinaire> produitveterinaires) {
		this.produitveterinaires = produitveterinaires;
	}

}
