package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Categorieprodelevage generated by hbm2java
 */
@Entity
@Table(name = "categorieprodelevage", schema = "public")
public class Categorieprodelevage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcatprodelevage;
	private String nom;
	private Set<Produitelevage> produitelevages = new HashSet(0);

	public Categorieprodelevage() {
	}

	public Categorieprodelevage(int idcatprodelevage) {
		this.idcatprodelevage = idcatprodelevage;
	}

	public Categorieprodelevage(int idcatprodelevage, String nom, Set<Produitelevage> produitelevages) {
		this.idcatprodelevage = idcatprodelevage;
		this.nom = nom;
		this.produitelevages = produitelevages;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idcatprodelevage", unique = true, nullable = false)
	public int getIdcatprodelevage() {
		return this.idcatprodelevage;
	}

	public void setIdcatprodelevage(int idcatprodelevage) {
		this.idcatprodelevage = idcatprodelevage;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorieprodelevage")
	@JsonIgnoreProperties("categorieprodelevage")
	public Set<Produitelevage> getProduitelevages() {
		return this.produitelevages;
	}

	public void setProduitelevages(Set<Produitelevage> produitelevages) {
		this.produitelevages = produitelevages;
	}

}
