package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Commandeclient generated by hbm2java
 */
@Entity
@Table(name = "commandeclient", schema = "public")
public class Commandeclient implements java.io.Serializable {

	private int numcommande;
	private Commande commande;
	private Client client;
	
	private Set<Lignecommandeclient> lignecommandeclients = new HashSet(0);
	
	/*private Set payementcomclients = new HashSet(0);
	private Set panierclients = new HashSet(0);*/

	public Commandeclient() {
	}

	public Commandeclient(Commande commande, Client client) {
		this.commande = commande;
		this.client = client;
		
	}

	

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "commande"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "numcommande", unique = true, nullable = false)
	public int getNumcommande() {
		return this.numcommande;
	}

	public void setNumcommande(int numcommande) {
		this.numcommande = numcommande;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "numuser", nullable = false)
	@JsonIgnoreProperties("commandeclients")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}
     
	
	

	
}
