package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.UUID;

import javax.persistence.*;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande")
public class Commande implements java.io.Serializable {

	private String id = UUID.randomUUID().toString();

	private Date datecommande ;
	private double montantTotal;
	private String description;
	private boolean confirmer ;
	private boolean livrer;

	//relation
	Payement payement;
	Client client;


	public Commande() {
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	public String getid() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecommande", length = 29)
	public Date getDatecommande() {
		return datecommande;
	}

	public void setDatecommande(Date datecommande) {
		this.datecommande = datecommande;
	}

	@Column(name = "confirmer")
	public boolean getConfirmer() {
		return confirmer;
	}

	public void setConfirmer(boolean confirmer) {
		this.confirmer = confirmer;
	}

	@Column(name = "livrer")
	public boolean getLivrer() {
		return this.livrer;
	}

	public void setLivrer(boolean livrer) {
		this.livrer = livrer;
	}


	@Column(name = "montanttotal", precision = 17, scale = 17)
	public double getMontantTotal() {
		return montantTotal;
	}

	public void setMontantTotal(double montantTotal) {
		this.montantTotal = montantTotal;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToOne
	public Payement getPayement() {
		return payement;
	}

	public void setPayement(Payement payement) {
		this.payement = payement;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}
}
