package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", schema = "public")
public class Commande implements java.io.Serializable {

	private int numcommande;
	private Date datecommande ;
	private boolean confirmer ;
	private boolean livrer;
	
	/*private Commandeeleveur commandeeleveur;
	private Commandeclient commandeclient;*/

	public Commande() {
	}

	public Commande(int numcommande) {
		this.numcommande = numcommande;
	}

	public Commande(int numcommande, Date datecommande,boolean confirmer ,boolean livrer) {
		this.numcommande = numcommande;
		this.datecommande = datecommande;
		this.livrer = livrer;
		this.confirmer = confirmer ;
		
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "numcommande", unique = true, nullable = false)
	public int getNumcommande() {
		return this.numcommande;
	}

	public void setNumcommande(int numcommande) {
		this.numcommande = numcommande;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecommande", length = 29)
	public Date getDatecommande() {
		return datecommande;
	}

	public void setDatecommande(Date datecommande) {
		this.datecommande = datecommande;
	}

	@Column(name = "confirmer")
	public boolean getConfirmer() {
		return confirmer;
	}

	public void setConfirmer(boolean confirmer) {
		this.confirmer = confirmer;
	}

	@Column(name = "livrer")
	public boolean getLivrer() {
		return this.livrer;
	}

	public void setLivrer(boolean livrer) {
		this.livrer = livrer;
	}

	

}
