package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", schema = "public")
public class Departement implements java.io.Serializable {

	private int iddepartement;
	private Region region;
	private String nomdepartement;
	private Set<Gie> gies = new HashSet(0);

	public Departement() {
	}

	public Departement(int iddepartement, Region region) {
		this.iddepartement = iddepartement;
		this.region = region;
	}

	public Departement(int iddepartement, Region region, String nomdepartement, Set<Gie> gies) {
		this.iddepartement = iddepartement;
		this.region = region;
		this.nomdepartement = nomdepartement;
		this.gies = gies;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "iddepartement", unique = true, nullable = false)
	public int getIddepartement() {
		return this.iddepartement;
	}

	public void setIddepartement(int iddepartement) {
		this.iddepartement = iddepartement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idregion", nullable = false)
	@JsonIgnoreProperties("departements")
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "nomdepartement", length = 254)
	public String getNomdepartement() {
		return this.nomdepartement;
	}

	public void setNomdepartement(String nomdepartement) {
		this.nomdepartement = nomdepartement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departement")
	@JsonIgnoreProperties("departement")
	public Set<Gie> getGies() {
		return this.gies;
	}

	public void setGies(Set<Gie> gies) {
		this.gies = gies;
	}

}
