package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Distributeur generated by hbm2java
 */
@Entity
@Table(name = "distributeur", schema = "public")
public class Distributeur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String numuser;
	private Utilisateur utilisateur;
	private Set<Produitelevage> produitelevages = new HashSet(0);

	public Distributeur() {
	}

	public Distributeur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Distributeur(Utilisateur utilisateur, Set<Produitelevage> produitelevages) {
		this.utilisateur = utilisateur;
		this.produitelevages = produitelevages;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utilisateur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "numuser", unique = true, nullable = false, length = 254)
	public String getNumuser() {
		return this.numuser;
	}

	public void setNumuser(String numuser) {
		this.numuser = numuser;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}
    
	

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "distributeur")
	@JsonIgnoreProperties("distributeur")
	public Set<Produitelevage> getProduitelevages() {
		return this.produitelevages;
	}

	public void setProduitelevages(Set<Produitelevage> produitelevages) {
		this.produitelevages = produitelevages;
	}

}
