package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Gie generated by hbm2java
 */
@Entity
@Table(name = "gie")
public class Gie implements java.io.Serializable {

	private String id = UUID.randomUUID().toString();
	private Departement departement;
	private String nom;
	private Set<Membre> membres = new HashSet(0);

	//private Set<Annoncegouvernemental> annoncegouvernementals = new HashSet(0);

	public Gie() {
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JsonIgnoreProperties("gies")
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "gie")
	@JsonIgnoreProperties("gie")
	public Set<Membre> getMembres() {
		return this.membres;
	}

	public void setMembres(Set<Membre> membres) {
		this.membres = membres;
	}
	
	/*@OneToMany(fetch = FetchType.EAGER, mappedBy = "gie")
	@JsonIgnoreProperties("gie")
	public Set<Annoncegouvernemental> getAnnoncegouvernementals() {
		return this.annoncegouvernementals;
	}

	public void setAnnoncegouvernementals(Set<Annoncegouvernemental> annoncegouvernementals) {
		this.annoncegouvernementals = annoncegouvernementals;
	}*/

}
