package org.sid.entities;
// Generated 26 mars 2019 14:00:12 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Lignecommandeclient generated by hbm2java
 */
@Entity
@Table(name = "lignecommandeclient", schema = "public")
public class Lignecommandeclient implements java.io.Serializable {

	private int idligneclient;
	private Commandeclient commandeclient;
	private Animal animal;
	private Integer quantite;
	private Double prixtotal;

	public Lignecommandeclient() {
	}

	

	
	public Lignecommandeclient(Commandeclient commandeclient, Animal animal) {
		super();
		this.commandeclient = commandeclient;
		this.animal = animal;
	}




	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idligneclient", unique = true, nullable = false)
	public int getIdligneclient() {
		return idligneclient;
	}

	public void setIdligneclient(int idligneclient) {
		this.idligneclient = idligneclient;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "numcommande", nullable = false)
	public Commandeclient getCommandeclient() {
		return this.commandeclient;
	}

	public void setCommandeclient(Commandeclient commandeclient) {
		this.commandeclient = commandeclient;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idanimal", nullable = false)
	@JsonIgnoreProperties("lignecommandeclients")
	public Animal getAnimal() {
		return this.animal;
	}

	public void setAnimal(Animal animal) {
		this.animal = animal;
	}

	

	@Column(name = "quantite")
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	@Column(name = "prixtotal", precision = 17, scale = 17)
	public Double getPrixtotal() {
		return this.prixtotal;
	}

	public void setPrixtotal(Double prixtotal) {
		this.prixtotal = prixtotal;
	}

}
