package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MembreId generated by hbm2java
 */
@Embeddable
public class MembreId implements java.io.Serializable {

	private String numuser;
	private int idgie;

	public MembreId() {
	}

	public MembreId(String numuser, int idgie) {
		this.numuser = numuser;
		this.idgie = idgie;
	}

	@Column(name = "numuser", nullable = false, length = 254)
	public String getNumuser() {
		return this.numuser;
	}

	public void setNumuser(String numuser) {
		this.numuser = numuser;
	}

	@Column(name = "idgie", nullable = false)
	public int getIdgie() {
		return this.idgie;
	}

	public void setIdgie(int idgie) {
		this.idgie = idgie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MembreId))
			return false;
		MembreId castOther = (MembreId) other;

		return ((this.getNumuser() == castOther.getNumuser()) || (this.getNumuser() != null
				&& castOther.getNumuser() != null && this.getNumuser().equals(castOther.getNumuser())))
				&& (this.getIdgie() == castOther.getIdgie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNumuser() == null ? 0 : this.getNumuser().hashCode());
		result = 37 * result + this.getIdgie();
		return result;
	}

}
