package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.UUID;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Membre generated by hbm2java
 */
@Entity
@Table(name = "membre", schema = "public")
public class Membre implements java.io.Serializable {

	private String id = UUID.randomUUID().toString();
	private Date dateadhesion;

	//relation
	private Gie gie;
	private Utilisateur utilisateur;

	public Membre() {
	}


	@Id
	@Column(name = "id", unique = true, nullable = false, length = 254)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id", nullable = false, insertable = false, updatable = false)
	@JsonIgnoreProperties("membres")
	public Gie getGie() {
		return this.gie;
	}

	public void setGie(Gie gie) {
		this.gie = gie;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateadhesion", length = 29)
	public Date getDateadhesion() {
		return this.dateadhesion;
	}

	public void setDateadhesion(Date dateadhesion) {
		this.dateadhesion = dateadhesion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id", nullable = false, insertable = false, updatable = false)
	@JsonIgnoreProperties("membres")
	public Utilisateur getUtilisateur() {
		return utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}
}
