package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Payementcomclient generated by hbm2java
 */
@Entity
@Table(name = "payementcomclient", schema = "public")
public class Payementcomclient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int idpayement;
	private Commandeclient commandeclient;
	private Date datepayement;
	private Double montant;

	public Payementcomclient() {
	}

	public Payementcomclient(int idpayement, Commandeclient commandeclient) {
		this.idpayement = idpayement;
		this.commandeclient = commandeclient;
	}

	public Payementcomclient(int idpayement, Commandeclient commandeclient, Date datepayement, Double montant) {
		this.idpayement = idpayement;
		this.commandeclient = commandeclient;
		this.datepayement = datepayement;
		this.montant = montant;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idpayement", unique = true, nullable = false)
	public int getIdpayement() {
		return this.idpayement;
	}

	public void setIdpayement(int idpayement) {
		this.idpayement = idpayement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "numcommande", nullable = false)
	@JsonIgnoreProperties("payementcomclients")
	public Commandeclient getCommandeclient() {
		return this.commandeclient;
	}

	public void setCommandeclient(Commandeclient commandeclient) {
		this.commandeclient = commandeclient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datepayement", length = 29)
	public Date getDatepayement() {
		return this.datepayement;
	}

	public void setDatepayement(Date datepayement) {
		this.datepayement = datepayement;
	}

	@Column(name = "montant", precision = 17, scale = 17)
	public Double getMontant() {
		return this.montant;
	}

	public void setMontant(Double montant) {
		this.montant = montant;
	}

}
