package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Produitelevage generated by hbm2java
 */
@Entity
@Table(name = "produitelevage", schema = "public")
public class Produitelevage implements java.io.Serializable {

	private String referenceproduit;
	private Produit produit;
	private Categorieprodelevage categorieprodelevage;
	private Distributeur distributeur;
	

	public Produitelevage() {
	}

	public Produitelevage(Produit produit, Categorieprodelevage categorieprodelevage, Distributeur distributeur) {
		this.produit = produit;
		this.categorieprodelevage = categorieprodelevage;
		this.distributeur = distributeur;
		
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "produit"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "referenceproduit", unique = true, nullable = false, length = 254)
	public String getReferenceproduit() {
		return this.referenceproduit;
	}

	public void setReferenceproduit(String referenceproduit) {
		this.referenceproduit = referenceproduit;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idcatprodelevage", nullable = false)
	@JsonIgnoreProperties("produitelevages")
	public Categorieprodelevage getCategorieprodelevage() {
		return this.categorieprodelevage;
	}

	public void setCategorieprodelevage(Categorieprodelevage categorieprodelevage) {
		this.categorieprodelevage = categorieprodelevage;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "numuser", nullable = false)
	@JsonIgnoreProperties("produitelevages")
	//@JsonIgnore
	public Distributeur getDistributeur() {
		return this.distributeur;
	}

	public void setDistributeur(Distributeur distributeur) {
		this.distributeur = distributeur;
	}

	

}
