package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", schema = "public")
public class Produit implements java.io.Serializable {

	private String id = UUID.randomUUID().toString();

	private String referenceProduit;
	private String photo;
	private String nom;
	private String description;
	private String modeEmploi;
	private double prix;
	private String typeProduit;
	private Date datePublication;
	private boolean selectionne;
	private boolean disponible;

	//relation
	Utilisateur utilisateur;
	Category category;

	//private Set<Lignecommandeeleveur> lignecommandeeleveurs = new HashSet(0);
	

	public Produit() {
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}


	@Column(name = "referenceproduit", unique = true, nullable = false, length = 254)
	public String getReferenceproduit() {
		return this.referenceProduit;
	}

	public void setReferenceproduit(String referenceproduit) {
		this.referenceProduit = referenceproduit;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	
	@Column(name = "photo") 
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "modeemploi", length = 254)
	public String getModeemploi() {
		return this.modeEmploi;
	}

	public void setModeemploi(String modeemploi) {
		this.modeEmploi = modeemploi;
	}

	@Column(name = "prix", precision = 17, scale = 17)
	public Double getPrix() {
		return this.prix;
	}

	public void setPrix(Double prix) {
		this.prix = prix;
	}

	@Column(name = "typeproduit", length = 254)
	public String getTypeproduit() {
		return this.typeProduit;
	}

	public void setTypeproduit(String typeproduit) {
		this.typeProduit = typeproduit;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datepublication", length = 29)
	public Date getDatepublication() {
		return datePublication;
	}

	public void setDatepublication(Date datepublication) {
		this.datePublication = datepublication;
	}


	@Column(name = "selectionne")
	public boolean isSelectionne() {
		return selectionne;
	}

	public void setSelectionne(boolean selectionne) {
		this.selectionne = selectionne;
	}

	@Column(name = "disponible")
	public boolean isDisponible() {
		return disponible;
	}

	public void setDisponible(boolean disponible) {
		this.disponible = disponible;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	//@JsonIgnoreProperties("produitelevages")
	//@JsonIgnore
	public Utilisateur getUtilisateur() {
		return utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}
}
