package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", schema = "public")
public class Produit implements java.io.Serializable {

	private String referenceproduit;
	private String photo;
	private String nom;
	private String description;
	private String modeemploi;
	private Double prix;
	private String typeproduit;
	private Date datepublication;
	private Set<Lignecommandeeleveur> lignecommandeeleveurs = new HashSet(0);
	

	public Produit() {
	}

	public Produit(String referenceproduit) {
		this.referenceproduit = referenceproduit;
	}

	public Produit(String referenceproduit, String nom, String description, String modeemploi, Double prix,
			String typeproduit,Date datepublicaton) {
		this.referenceproduit = referenceproduit;
		this.nom = nom;
		this.description = description;
		this.modeemploi = modeemploi;
		this.prix = prix;
		this.typeproduit = typeproduit;
	    this.datepublication = datepublicaton ;
		
	}

	@Id

	@Column(name = "referenceproduit", unique = true, nullable = false, length = 254)
	public String getReferenceproduit() {
		return this.referenceproduit;
	}

	public void setReferenceproduit(String referenceproduit) {
		this.referenceproduit = referenceproduit;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	
	@Column(name = "photo") 
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "modeemploi", length = 254)
	public String getModeemploi() {
		return this.modeemploi;
	}

	public void setModeemploi(String modeemploi) {
		this.modeemploi = modeemploi;
	}

	@Column(name = "prix", precision = 17, scale = 17)
	public Double getPrix() {
		return this.prix;
	}

	public void setPrix(Double prix) {
		this.prix = prix;
	}

	@Column(name = "typeproduit", length = 254)
	public String getTypeproduit() {
		return this.typeproduit;
	}

	public void setTypeproduit(String typeproduit) {
		this.typeproduit = typeproduit;
	}

	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "produit")
	@JsonIgnoreProperties("produit")
	public Set<Lignecommandeeleveur> getLignecommandeeleveurs() {
		return this.lignecommandeeleveurs;
	}

	public void setLignecommandeeleveurs(Set<Lignecommandeeleveur> lignecommandeeleveurs) {
		this.lignecommandeeleveurs = lignecommandeeleveurs;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datepublication", length = 29)
	public Date getDatepublication() {
		return datepublication;
	}

	public void setDatepublication(Date datepublication) {
		this.datepublication = datepublication;
	}

	

}
