package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", schema = "public")
public class Region implements java.io.Serializable {

	private int idregion;
	private String nomregion;
	private Set<Departement> departements = new HashSet(0);

	public Region() {
	}

	public Region(int idregion) {
		this.idregion = idregion;
	}

	public Region(int idregion, String nomregion, Set<Departement> departements) {
		this.idregion = idregion;
		this.nomregion = nomregion;
		this.departements = departements;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idregion", unique = true, nullable = false)
	public int getIdregion() {
		return this.idregion;
	}

	public void setIdregion(int idregion) {
		this.idregion = idregion;
	}

	@Column(name = "nomregion", length = 254)
	public String getNomregion() {
		return this.nomregion;
	}

	public void setNomregion(String nomregion) {
		this.nomregion = nomregion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "region")
	@JsonIgnoreProperties("region")
	public Set<Departement> getDepartements() {
		return this.departements;
	}

	public void setDepartements(Set<Departement> departements) {
		this.departements = departements;
	}

}
