package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Typeanimal generated by hbm2java
 */
@Entity
@Table(name = "typeanimal", schema = "public")
public class Typeanimal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtypeanimal;
	private String libelle;
	private List<Animal> animals = new ArrayList();

	public Typeanimal() {
	}

	public Typeanimal(int idtypeanimal) {
		this.idtypeanimal = idtypeanimal;
	}

	public Typeanimal(int idtypeanimal, String libelle, List<Animal> animals) {
		this.idtypeanimal = idtypeanimal;
		this.libelle = libelle;
		this.animals = animals;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idtypeanimal", unique = true, nullable = false)
	public int getIdtypeanimal() {
		return this.idtypeanimal;
	}

	public void setIdtypeanimal(int idtypeanimal) {
		this.idtypeanimal = idtypeanimal;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "typeanimal")
	@JsonIgnoreProperties("typeanimal")
	//@JsonIgnore
	public List<Animal> getAnimals() {
		return this.animals;
	}

	public void setAnimals(List<Animal> animals) {
		this.animals = animals;
	}

}
