package org.sid.entities;
// Generated 5 mars 2019 12:53:42 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", schema = "public")
public class Utilisateur implements java.io.Serializable {

	private String numuser;
	private Role role;
	private String nom;
	private String prenom;
	private String adresse;
	private String email;
	private String telephone;
	private String login;
	private String password;
	private String profil;
	

	public Utilisateur() {
	}

	public Utilisateur(String numuser, Role role) {
		this.numuser = numuser;
		this.role = role;
	}

	public Utilisateur(String numuser, Role role, String nom, String prenom, String adresse, String email,
			String telephone, String login, String password, String profil) {
		this.numuser = numuser;
		this.role = role;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.email = email;
		this.telephone = telephone;
		this.login = login;
		this.password = password;
		this.profil = profil;
		
	}

	@Id

	@Column(name = "numuser", unique = true, nullable = false, length = 254)
	public String getNumuser() {
		return this.numuser;
	}

	public void setNumuser(String numuser) {
		this.numuser = numuser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idrole", nullable = false)
	@JsonIgnoreProperties("utilisateurs")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "email", length = 254,unique=true)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", length = 254)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "login", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 254)
	@JsonProperty(access= JsonProperty.Access.WRITE_ONLY)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "profil", length = 254)
	public String getProfil() {
		return this.profil;
	}

	public void setProfil(String profil) {
		this.profil = profil;
	}

	
}
